name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Hello NN smoke test
        run: python -c "import src.hello_nn as m; print(m.smoke_test())"
      
      - name: CNN smoke test (subset)
        run: python -c "import src.train_fashion_mnist as t; print(t.smoke_test('cnn'))"
      
      - name: Export sanity check
        run: |
          python -m src.train_fashion_mnist --epochs 2 --batch-size 128 --subset-train 2000 --seed 0 --device cpu --model cnn --outdir artifacts
          python -m src.export --model auto --ckpt artifacts/checkpoints/best.pt --outdir artifacts/export