name: tests
on:
  push:
    branches: [ main, master ]
    paths: [ "src/**", "scripts/**", "tests/**", "Makefile", "pyproject.toml", "requirements*.txt" ]
  pull_request:
    paths: [ "src/**", "scripts/**", "tests/**" ]

jobs:
  python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-timeout pytest-cov coverage
      - name: Headless env
        run: |
          echo "SDL_VIDEODRIVER=null" >> $GITHUB_ENV
          echo "SDL_AUDIODRIVER=dummy" >> $GITHUB_ENV
      - name: Fast tests (PRs)
        if: github.event_name == 'pull_request'
        run: pytest -m "unit or smoke" --cov=src --cov-report=term-missing
      - name: Full tests (push to main)
        if: github.event_name == 'push'
        run: pytest -m "unit or smoke or rl or cli" --cov=src --cov-report=xml:artifacts/coverage.xml --cov-report=term